### ISSUE TITLE
[Feature request] TMS/WMTS request.

### ISSUE THREAD

**Issue by LaoshuBaby** [kongying-tavern/yuan-shen-map#14]
## Feature request

希望能以TMS或者WMTS形式的瓦片，想试图在JOSM里添加为瓦片源，尝试用OSM的数据形式重绘提瓦特地图

### Description

![图片](https://user-images.githubusercontent.com/42690037/139518589-668c312e-d82d-4ac5-8a6c-7f0128752eb8.png)
![图片](https://user-images.githubusercontent.com/42690037/139518875-3bb489cb-37ad-46d5-933e-4bf7e9b57c35.png)

**Comment by peaceshi** [comment]
> ## Feature request
> 希望能以TMS或者WMTS形式的瓦片，想试图在JOSM里添加为瓦片源，尝试用OSM的数据形式重绘提瓦特地图
> 
> ### Description
> ![图片](https://user-images.githubusercontent.com/42690037/139518589-668c312e-d82d-4ac5-8a6c-7f0128752eb8.png) ![图片](https://user-images.githubusercontent.com/42690037/139518875-3bb489cb-37ad-46d5-933e-4bf7e9b57c35.png)

https://github.com/kongying-tavern/map-tile-generator/blob/master/RFC_UseOrthographicCoords.md

https://github.com/kongying-tavern/yuan-shen-map/blob/189dc9e4d2ee9d60dd837731e87d99572d69fe74/Yuanshenditu/js/index2.js#L3-L33

Because of the non-geographic tiles, you can do that by yourself if you want to be like TMS or WMTS.

**Comment by LaoshuBaby** [comment]
> https://github.com/kongying-tavern/map-tile-generator/blob/master/RFC_UseOrthographicCoords.md

I noticed that those tiles are rendered by this website

http://ysmap.projectxero.top/?url=yuanshen.site/default.json&size=4096

This rendering process is very interesting. I would like to know what data source it is based on.
If I want to set up a similar rendering server like that locally, how should I prepare? 
Or is it actually just processing of image tiles from the observation-pivot using super-resolution methods such as waifu2x?
Because it provides tiles that support retina, so I raised this guess.

**Comment by XeroAlpha** [comment]
> > https://github.com/kongying-tavern/map-tile-generator/blob/master/RFC_UseOrthographicCoords.md
> 
> I noticed that those tiles are rendered by this website
> 
> http://ysmap.projectxero.top/?url=yuanshen.site/default.json&size=4096
> 
> This rendering process is very interesting. I would like to know what data source it is based on. If I want to set up a similar rendering server like that locally, how should I prepare? Or is it actually just processing of image tiles from the observation-pivot using super-resolution methods such as waifu2x? Because it provides tiles that support retina, so I raised this guess.

感谢关注我整的这个地图瓦片生成器。不过我想先提一嘴，这个[ysmap.projectxero.top](https://gitee.com/projectxero/ysmaprender)并不是用来生成瓦片而是用来渲染带有修饰图层的大地图（或者大地图的一部分）的，其图片数据来源也并非是来自这个地图瓦片生成器，而是来自于早期版本地图的瓦片。
地图瓦片生成器本身需要提供大地图的完整图片或者几张可以被拼成大地图的图片（以下称“原始图片”），这些图片我从其他途径得到，没有commit到repo里。地图瓦片生成器生成的瓦片清晰度并不能比原始图片更高，提高分辨率所使用的方法也并不是waifu2x等方法，只是简单的双线性插值。支持retina只是因为leaflet支持retina，所以顺带整了下。
