### ISSUE TITLE
[Bug report] Item_Features.js auto generation needs review.

### ISSUE THREAD

**Issue by peaceshi** [kongying-tavern/yuan-shen-map#16]
https://github.com/kongying-tavern/yuan-shen-map/blob/master/tools/genGeoJson.mjs

I am not sure the reason of bug. 

https://github.com/kongying-tavern/yuan-shen-map/blob/5d3577331144b291195ea1522ef8f91d2703d930/tools/genGeoJson.mjs#L87-L97

**Comment by langyo** [comment]
I have roughly understood the purpose of this part of the source code.

Why not store the file directly in a JSON file?

**Comment by boxsnake** [comment]
> I have roughly understood the purpose of this part of the source code.
> 
> Why not store the file directly in a JSON file?

Since some further data are computed based on the variable `originJsonArr`, and the code is too hard to be modified.

We just simply extract this variable part into another file called `Item_Features.js`.

**Comment by langyo** [comment]
> > I have roughly understood the purpose of this part of the source code.
> > Why not store the file directly in a JSON file?
> 
> This generated `Item_Features.js` is originally the trailing part of `Item_Json.js`. We just simply split the file into two files `Item_Json.js` and `Item_Features.js`, and load in `<script>` tags in sequence.
> 
> Former:
> 
> ```
> <script src="Item_Json.js"></script>
> ```
> 
> Now:
> 
> ```
> <script src="Item_Json.js"></script>
> <script src="Item_Features.js"></script>
> ```
> 
> Since it is too hard to make modifications in this project, we did not do anything more.
> 
> If we made it to a JSON file, we have to load it by AJAX in the web pages. However, we are not sure about the side effects of doing this.

I have no idea for it...

However, we can use Webpack's own packer to split all of these data into some source code files automatically, what can communicate with each other by the global scope's variants.

Maybe we should use the other's library instead of our works about it.

**Comment by boxsnake** [comment]
@langyo 

Webpack is hard for this v1 map. The v1 map is totally written in raw html, js and css. Webpack stuff will be a totally refactor.

**Comment by boxsnake** [comment]
@langyo 

Webpack is hard for this v1 map. The v1 map is totally written in raw html, js and css. Webpack stuff will be a totally refactor.
