### ISSUE TITLE
[Feature request] 希望地图不要强制回正

### ISSUE THREAD

**Issue by GitHuberRich** [kongying-tavern/yuan-shen-map#18]
## Feature request
有时候要查看地图的角落，拖曳后会被强制回正，非常的不方便查看，请去掉强制回正，谢谢！
或者可以增加一键回正，或是自动回正的开关
另外，点击区域名称tab的时候，希望可以自动移到该地区，或者双击后移动
例如我双击蒙德tab，则地图拉到蒙德城，这个功能官方已经要作了，您们可以抢先做出来，哈哈

**Comment by peaceshi** [comment]
1. 回正是latLngBounds问题，地图底图右侧边界太近了。暂时无法确定修改是否有副作用。
2. 区域跳转使用flyTo即可实现。
#16

**Comment by A8Chann** [comment]
可以，这就更

**Comment by A8Chann** [comment]
更新完成
