### ISSUE TITLE
[Feature request] Add leaflet flyto to area lables.

### ISSUE THREAD

**Issue by peaceshi** [kongying-tavern/yuan-shen-map#19]
### Description

https://leafletjs.com/reference.html#map-flyto

### Proposed Solution

Add `map.flyTo()` function to files below.

https://github.com/kongying-tavern/yuan-shen-map/blob/216658b100b58a0e5409c0bf85933221ef96529a/Yuanshenditu/index.html#L5069
https://github.com/kongying-tavern/yuan-shen-map/blob/216658b100b58a0e5409c0bf85933221ef96529a/Yuanshenditu/index_en.html#L5011
https://github.com/kongying-tavern/yuan-shen-map/blob/216658b100b58a0e5409c0bf85933221ef96529a/Yuanshenditu/index_jp.html#L5019
https://github.com/kongying-tavern/yuan-shen-map/blob/216658b100b58a0e5409c0bf85933221ef96529a/Yuanshenditu/index_old.html#L5063

**Comment by A8Chann** [comment]
ok
