### ISSUE TITLE
客戶端佔用過多系統資源

### ISSUE THREAD

**Issue by seriaati** [kongying-tavern/yuan-shen-map#29]
我下載了原神地圖的客戶端，但這個佔用的系統資院我得說真的有點太多了，這已經是開了另一個原神了吧。
![image](https://user-images.githubusercontent.com/61446626/158087316-21e01325-45f1-42f7-aa1c-90cf9c77721f.png)

**Comment by peaceshi** [comment]
> 我下載了原神地圖的客戶端，但這個佔用的系統資院我得說真的有點太多了，這已經是開了另一個原神了吧。 ![image](https://user-images.githubusercontent.com/61446626/158087316-21e01325-45f1-42f7-aa1c-90cf9c77721f.png)

![image](https://user-images.githubusercontent.com/10380828/158323827-e3f388f2-8f9b-4f76-9f51-07725f910487.png)

https://support.qq.com/products/321980/faqs/97183
