### ISSUE TITLE
Desktop client resets position and filters

### ISSUE THREAD

**Issue by mveselov-de** [kongying-tavern/yuan-shen-map#6]
Hi.

Sorry, I couldn't figure out how to register on QQ, so writing here. I have persistent bug on windows client, where my map position, zoom and selected markers are being reset to some fixed value - Inazuma with nothing selected. This is happening regularly, I think after a certain period of inactivity, 10, maybe 15 mins. I have cloud sync enabled, so maybe this is root cause.

**Comment by peaceshi** [comment]
Sorry for the bad user experience.
we need more info.
1. client version, please use latest version.
2. video capture.

you can also join our discord https://discord.gg/yJUCYDNm

**Comment by mveselov-de** [comment]
Hi - that discord link is actually invalid, can you please post a new one ?

**Comment by peaceshi** [comment]
> Hi - that discord link is actually invalid, can you please post a new one ?

https://yuanshen.site/docs/en/

https://discord.gg/fR5T4Ekf
